/**
 * Display-only localisation for strings supplied by CyberChef's generated
 * OperationConfig. Recipe operation names and argument values must stay in
 * English because they are part of the worker protocol.
 */

type Language = 'en' | 'zh';

export function cyberChefLanguage(language?: string): Language {
  return language?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}

const ZH_CATEGORIES: Record<string, string> = {
  Favourites: '收藏',
  'Data format': '数据格式',
  'Encryption / Encoding': '加密 / 编码',
  'Public Key': '公钥',
  'Arithmetic / Logic': '算术 / 逻辑',
  Networking: '网络',
  Language: '语言',
  Utils: '实用工具',
  'Date / Time': '日期 / 时间',
  Extractors: '提取器',
  Compression: '压缩',
  Hashing: '哈希',
  'Code tidy': '代码整理',
  Forensics: '数字取证',
  Multimedia: '多媒体',
  Other: '其他',
  'Flow control': '流程控制',
};

/** Frequently used operations whose natural Chinese rendering cannot be
 * produced reliably by grammatical prefix/suffix rules. */
const ZH_OPERATION_LABELS: Record<string, string> = {
  'Argon2 compare': 'Argon2 比较',
  'Automated Validation Test Op': '自动验证测试操作',
  'Avro to JSON': 'Avro 转 JSON',
  'BSON deserialise': 'BSON 反序列化',
  'BSON serialise': 'BSON 序列化',
  'Bcrypt compare': 'Bcrypt 比较',
  'Bcrypt parse': 'Bcrypt 解析',
  'Bit shift left': '位左移',
  'Bit shift right': '位右移',
  'Blur Image': '模糊图像',
  'Crop Image': '裁剪图像',
  'CSS selector': 'CSS 选择器',
  'Convert to NATO alphabet': '转换为 NATO 音标字母',
  'DNS over HTTPS': 'HTTPS DNS',
  'Decode text': '解码文本',
  'Decode NetBIOS Name': '解码 NetBIOS 名称',
  'Dither Image': '图像抖动',
  Divide: '除法',
  'ELF Info': 'ELF 信息',
  'Encode text': '编码文本',
  'Encode NetBIOS Name': '编码 NetBIOS 名称',
  'Escape string': '转义字符串',
  'Extract Audio Metadata': '提取音频元数据',
  'From Braille': '从盲文解码',
  'From Case Insensitive Regex': '从不区分大小写的正则表达式还原',
  'From Charcode': '从字符码还原',
  'From Float': '从浮点数还原',
  'From HTML Entity': '从 HTML 实体解码',
  'From Hex Content': '从十六进制内容还原',
  'From Hexdump': '从十六进制转储还原',
  'From Morse Code': '从摩斯码解码',
  'From Octal': '从八进制还原',
  'From Quoted Printable': '从 Quoted-Printable 解码',
  'From UNIX Timestamp': '从 UNIX 时间戳转换',
  'Generic Code Beautify': '通用代码美化',
  'Generate De Bruijn Sequence': '生成 De Bruijn 序列',
  'Generate Lorem Ipsum': '生成 Lorem Ipsum 占位文本',
  'Generate QR Code': '生成二维码',
  'HTML To Text': 'HTML 转文本',
  'HTTP request': 'HTTP 请求',
  'Heatmap chart': '热力图',
  'Hex Density chart': '十六进制密度图',
  'Hex to Object Identifier': '十六进制转对象标识符',
  'IPv6 Transition Addresses': 'IPv6 过渡地址',
  'Image Filter': '图像滤镜',
  'Image Opacity': '图像不透明度',
  'Invert Image': '反色图像',
  'JPath expression': 'JPath 表达式',
  'Jsonata Query': 'Jsonata 查询',
  'MIME Decoding': 'MIME 解码',
  'Microsoft Script Decoder': 'Microsoft 脚本解码器',
  'Object Identifier to Hex': '对象标识符转十六进制',
  'Parse ASN.1 hex string': '解析 ASN.1 十六进制字符串',
  'Parse DateTime': '解析日期时间',
  'Parse Ethernet frame': '解析以太网帧',
  'Parse IP range': '解析 IP 范围',
  'Parse ObjectID timestamp': '解析 ObjectID 时间戳',
  'Parse QR Code': '解析二维码',
  'Parse SSH Host Key': '解析 SSH 主机密钥',
  'Parse TLS record': '解析 TLS 记录',
  'Parse UNIX file permissions': '解析 UNIX 文件权限',
  'Parse User Agent': '解析用户代理',
  'Parse colour code': '解析颜色代码',
  'RC4 Drop': 'RC4 丢弃',
  'Randomize Colour Palette': '随机化调色板',
  'Render Markdown': '渲染 Markdown',
  'Remove ANSI Escape Codes': '移除 ANSI 转义码',
  'Remove Diacritics': '移除变音符号',
  'Remove null bytes': '移除空字节',
  'Remove whitespace': '移除空白',
  'Rotate left': '循环左移',
  'Rotate right': '循环右移',
  'Scatter chart': '散点图',
  'Series chart': '序列图',
  'Set Difference': '集合差集',
  'Set Intersection': '集合交集',
  'Set Union': '集合并集',
  'Sharpen Image': '锐化图像',
  'Show Base64 offsets': '显示 Base64 偏移量',
  'Show on map': '在地图上显示',
  'Split Colour Channels': '分离颜色通道',
  'Standard Deviation': '标准差',
  'Syntax highlighter': '语法高亮',
  'Strip HTML tags': '去除 HTML 标签',
  'Text Encoding Brute Force': '文本编码暴力识别',
  'To Braille': '编码为盲文',
  'To Camel case': '转为小驼峰命名',
  'To Case Insensitive Regex': '转为不区分大小写的正则表达式',
  'To Charcode': '转为字符码',
  'To Float': '转为浮点数',
  'To HTML Entity': '编码为 HTML 实体',
  'To Hex Content': '转为十六进制内容',
  'To Hexdump': '转为十六进制转储',
  'To Kebab case': '转为短横线命名',
  'To Lower case': '转为小写',
  'To Morse Code': '编码为摩斯码',
  'To Octal': '转为八进制',
  'To Quoted Printable': '编码为 Quoted-Printable',
  'To Snake case': '转为下划线命名',
  'To Table': '转为表格',
  'To UNIX Timestamp': '转为 UNIX 时间戳',
  'To Upper case': '转为大写',
  'Translate DateTime Format': '转换日期时间格式',
  'Unicode Text Format': 'Unicode 文本格式',
  'Unescape string': '取消字符串转义',
  Untar: '解包 Tar',
  Unzip: '解压 Zip',
  'XPath expression': 'XPath 表达式',
  'YARA Rules': 'YARA 规则',
  'Zlib Deflate': 'Zlib 压缩',
  'Zlib Inflate': 'Zlib 解压',
};

/** Whole labels whose natural Chinese rendering cannot be produced well by
 * word-level replacement. This also covers the terse flow-control operations.
 */
const ZH_EXACT: Record<string, string> = {
  ...ZH_OPERATION_LABELS,
  'Add Text To Image': '向图像添加文字',
  'Add line numbers': '添加行号',
  'Alternating Caps': '大小写交替',
  'Analyse UUID': '分析 UUID',
  'Analyse hash': '分析哈希',
  'Atbash Cipher': 'Atbash 密码',
  Bombe: 'Bombe 破译机',
  'Caesar Box Cipher': '凯撒方框密码',
  'Caret/M-decode': 'Caret/M 解码',
  'Cartesian Product': '笛卡尔积',
  'Change IP format': '更改 IP 格式',
  'Chi Square': '卡方检验',
  Colossus: '巨像机',
  Comment: '注释',
  'Conditional Jump': '条件跳转',
  'Contain Image': '等比容纳图像',
  'Convert Leet Speak': '转换 Leet 语',
  'Convert co-ordinate format': '转换坐标格式',
  'Count occurrences': '统计出现次数',
  'Cover Image': '等比覆盖图像',
  'DateTime Delta': '日期时间差',
  'Dechunk HTTP response': '解析 HTTP 分块响应',
  Diff: '差异比较',
  'Drop bytes': '丢弃字节',
  'Drop nth bytes': '丢弃每第 n 个字节',
  Enigma: '恩尼格玛机',
  Entropy: '信息熵',
  'Escape Smart Characters': '转义智能字符',
  'Expand alphabet range': '展开字母范围',
  'Fang URL': '恢复 URL',
  'File Tree': '文件树',
  Filter: '过滤',
  'Find / Replace': '查找 / 替换',
  'Flip Image': '翻转图像',
  Fork: '分流',
  'Frequency distribution': '频率分布',
  'Fuzzy Match': '模糊匹配',
  'Get All Casings': '获取所有大小写组合',
  'Get Time': '获取时间',
  Head: '取开头',
  'Index of Coincidence': '重合指数',
  Jump: '跳转',
  Label: '标签',
  Lorenz: '洛伦兹密码机',
  Magic: '自动识别（Magic）',
  Mean: '平均值',
  Median: '中位数',
  Merge: '合并',
  'Multiple Bombe': '多轮 Bombe 破译',
  Multiply: '乘法',
  'Normalise Image': '图像归一化',
  'Normalise Unicode': '规范化 Unicode',
  Numberwang: '数字游戏（Numberwang）',
  'Offset checker': '偏移量检查',
  'Optical Character Recognition': '光学字符识别（OCR）',
  'P-list Viewer': 'P-list 查看器',
  'Parity Bit': '奇偶校验位',
  'Play Media': '播放媒体',
  'Power Set': '幂集',
  'Public Key from Certificate': '从证书提取公钥',
  'Public Key from Private Key': '从私钥提取公钥',
  'Pseudo-Random Integer Generator': '伪随机整数生成器',
  'Pseudo-Random Number Generator': '伪随机数生成器',
  'Raw Deflate': '原始 Deflate 压缩',
  'Raw Inflate': '原始 Deflate 解压',
  Register: '寄存器',
  'Regular expression': '正则表达式',
  Return: '返回',
  Reverse: '反转',
  'Scan for Embedded Files': '扫描嵌入文件',
  Shuffle: '随机打乱',
  Sleep: '延时',
  Sort: '排序',
  Split: '拆分',
  Strings: '提取字符串',
  Subsection: '截取片段',
  Substitute: '替换',
  Subtract: '减法',
  Sum: '求和',
  'Swap case': '交换大小写',
  'Swap endianness': '交换字节序',
  'Symmetric Difference': '对称差集',
  Tail: '取末尾',
  'Take bytes': '取字节',
  'Take nth bytes': '取每第 n 个字节',
  'Text-Integer Conversion': '文本-整数转换',
  'UNIX Timestamp to Windows Filetime': 'UNIX 时间戳转 Windows 文件时间',
  Unique: '去重',
  'View Bit Plane': '查看位平面',
  'Windows Filetime to UNIX Timestamp': 'Windows 文件时间转 UNIX 时间戳',
  Wrap: '换行包装',
  'XKCD Random Number': 'XKCD 随机数',
};

const OP_PREFIXES: Array<[string, string]> = [
  ['Generate all ', '生成全部'],
  ['Generate ', '生成'],
  ['Extract ', '提取'],
  ['Remove ', '移除'],
  ['Render ', '渲染'],
  ['Convert ', '转换'],
  ['Compare ', '比较'],
  ['Decode ', '解码'],
  ['Encode ', '编码'],
  ['Detect ', '检测'],
  ['Derive ', '派生'],
  ['Disassemble ', '反汇编'],
  ['Defang ', '脱敏'],
  ['Escape ', '转义'],
  ['Unescape ', '取消转义'],
  ['Format ', '格式化'],
  ['Group ', '分组'],
  ['Parse ', '解析'],
  ['Strip ', '去除'],
  ['Show ', '显示'],
  ['Randomize ', '随机化'],
  ['Resize ', '调整大小'],
  ['Rotate ', '旋转'],
  ['Translate ', '转换'],
];

const OP_SUFFIXES: Array<[string, string]> = [
  [' Decrypt and Verify', ' 解密并验证'],
  [' Encrypt and Sign', ' 加密并签名'],
  [' Signature Conversion', ' 签名转换'],
  [' Brute Force', ' 暴力破解'],
  [' Key Unwrap', ' 密钥解包'],
  [' Key Wrap', ' 密钥包装'],
  [' Key Pair', ' 密钥对'],
  [' Decompress', ' 解压'],
  [' Deserialise', ' 反序列化'],
  [' Deserialize', ' 反序列化'],
  [' Serialise', ' 序列化'],
  [' Serialize', ' 序列化'],
  [' Beautify', ' 美化'],
  [' Minify', ' 压缩'],
  [' Compress', ' 压缩'],
  [' Decrypt', ' 解密'],
  [' Encrypt', ' 加密'],
  [' Decode', ' 解码'],
  [' Encode', ' 编码'],
  [' Checksum', ' 校验和'],
  [' Fingerprint', ' 指纹'],
  [' Distance', ' 距离'],
  [' Viewer', ' 查看器'],
  [' Parser', ' 解析器'],
  [' Conversion', ' 转换'],
  [' Recognition', ' 识别'],
  [' distribution', ' 分布'],
  [' Sign', ' 签名'],
  [' Verify', ' 验证'],
  [' Hash', ' 哈希'],
  [' MAC', ' 消息认证码'],
  [' chart', '图'],
];

/** Common CyberChef ingredient and option text. Exact matches are preferred;
 * word-level entries below handle generated combinations and parentheticals.
 */
const ZH_TERMS: Record<string, string> = {
  'Additional Authenticated Data': '附加认证数据',
  'Associated Data': '关联数据',
  'Case insensitive': '不区分大小写',
  'Case sensitive matching': '区分大小写匹配',
  'Error correction': '容错级别',
  'Input format string': '输入格式字符串',
  'Output format string': '输出格式字符串',
  'Internationalised domain name': '国际化域名',
  'Maintain aspect ratio': '保持宽高比',
  'Make first row header': '将首行作为表头',
  'Private key of recipient': '接收方私钥',
  'Private key of signer': '签名方私钥',
  'Public key of recipient': '接收方公钥',
  'Public key of signer': '签名方公钥',
  'Remove non-alphabet chars': '移除非字母字符',
  'Treat "+" as space': '将“+”视为空格',
  'Use checking machine': '使用检查机',
  'All hashes': '所有哈希',
  'All-zero group char': '全零组字符',
  'Allow large queries': '允许大型查询',
  'Apply to each line': '应用于每一行',
  'Autoconvert URLs to links': '自动将 URL 转为链接',
  'Convert all characters': '转换所有字符',
  'Enable syntax highlighting': '启用语法高亮',
  'Ignore whitespace': '忽略空白',
  'Include IV in output': '在输出中包含 IV',
  'Only show the subnets': '仅显示子网',
  'Open links in new tab.': '在新标签页打开链接',
  'Output valid JSON': '输出有效 JSON',
  'Preserve comments': '保留注释',
  'Remove excess line breaks': '移除多余换行',
  'Report errors and try to continue': '报告错误并尝试继续',
  'Sort Object Keys': '对对象键排序',
  'Treat as UTC': '按 UTC 处理',
  'Upper case hex': '大写十六进制',
  'Uppercase hex': '大写十六进制',
  'Add': '添加',
  'Algorithm': '算法',
  'Alphabet': '字母表',
  'Amount': '数量',
  'Architecture': '架构',
  'Audio': '音频',
  'Base': '进制',
  'Bit': '位',
  'Block size': '分组大小',
  'Blue': '蓝色',
  'Brightness': '亮度',
  'By': '方式',
  'Byte Length': '字节长度',
  'Bytes per line': '每行字节数',
  'Character': '字符',
  'Ciphertext': '密文',
  'Colour': '颜色',
  'Comment': '注释',
  'Compression Format': '压缩格式',
  'Compression Mode': '压缩模式',
  'Contrast': '对比度',
  'Counter': '计数器',
  'Crib': '猜测明文',
  'Curve': '曲线',
  'Data format': '数据格式',
  'Days': '天',
  'Delimiter': '分隔符',
  'Depth': '深度',
  'Direction': '方向',
  'Encoding': '编码',
  'Endianness': '字节序',
  'Extractor': '提取器',
  'Field delimiter': '字段分隔符',
  'Filename': '文件名',
  'Filter type': '过滤类型',
  'Find': '查找',
  'Format': '格式',
  'Formatted': '已格式化',
  'Global match': '全局匹配',
  'Green': '绿色',
  'Hash': '哈希',
  'Header': '头部',
  'Height': '高度',
  'Hours': '小时',
  'Hue': '色相',
  'IV': '初始化向量（IV）',
  'Ignore case': '忽略大小写',
  'Image Format': '图像格式',
  'Input': '输入',
  'Input Format': '输入格式',
  'Input Type': '输入类型',
  'Iterations': '迭代次数',
  'Key': '密钥',
  'Key length': '密钥长度',
  'Key size': '密钥大小',
  'Language': '语言',
  'Length': '长度',
  'Lightness': '明度',
  'Line feeds (\\n)': '换行符（\\n）',
  'Match': '匹配',
  'Memory (KiB)': '内存（KiB）',
  'Message': '消息',
  'Method': '方法',
  'Minutes': '分钟',
  'Mode': '模式',
  'Name': '名称',
  'Nonce': '随机数（Nonce）',
  'Number': '数字',
  'Offset': '偏移量',
  'Opacity (%)': '不透明度（%）',
  'Order': '顺序',
  'Output': '输出',
  'Output Encoding': '输出编码',
  'Output Format': '输出格式',
  'Padding': '填充',
  'Passphrase': '口令',
  'Password': '密码',
  'Pattern': '模式',
  'Plaintext': '明文',
  'Position': '位置',
  'Precision': '精度',
  'Prefix': '前缀',
  'Private Key': '私钥',
  'Public Key': '公钥',
  'Radius': '半径',
  'Red': '红色',
  'Reflector': '反射器',
  'Regex': '正则表达式',
  'Replace': '替换',
  'Result delimiter': '结果分隔符',
  'Reverse': '反转',
  'Rotation amount (degrees)': '旋转角度（度）',
  'Rounds': '轮数',
  'Salt': '盐值',
  'Saturation': '饱和度',
  'Scheme': '方案',
  'Search': '搜索',
  'Seconds': '秒',
  'Seed': '种子',
  'Signed': '有符号',
  'Size': '大小',
  'Sort': '排序',
  'Start': '开始',
  'Strict mode': '严格模式',
  'Tabs': '制表符',
  'Text': '文本',
  'Threshold': '阈值',
  'Type': '类型',
  'Unique': '去重',
  'Unit': '单位',
  'URL': 'URL',
  'Variant': '变体',
  'Version': '版本',
  'Width': '宽度',
  'Work factor': '工作因子',
  'X position': 'X 坐标',
  'Y position': 'Y 坐标',
  'Yes': '是',
  'No': '否',
  'True': '真',
  'False': '假',
  'Space': '空格',
  'Comma': '逗号',
  'Semi-colon': '分号',
  'Colon': '冒号',
  'Line feed': '换行符',
  'Decimal': '十进制',
  'Binary': '二进制',
  'Hex': '十六进制',
  'Upper': '大写',
  'Lower': '小写',
  'Left': '左',
  'Right': '右',
  'None': '无',
  'Auto': '自动',
};

const WORD_TERMS: Array<[RegExp, string]> = [
  [/\binitial\b/gi, '初始'], [/\balphabet\b/gi, '字母表'], [/\battempt\b/gi, '尝试'],
  [/\bkeep\b/gi, '保留'], [/\bblock\b/gi, '分组'], [/\bbuffer\b/gi, '缓冲区'],
  [/\bexpansion\b/gi, '扩展'], [/\bcell\b/gi, '单元格'], [/\bcode\b/gi, '代码'],
  [/\bcolon\b/gi, '冒号'], [/\bpattern\b/gi, '模式'], [/\bcomments?\b/gi, '注释'],
  [/\bcompression\b/gi, '压缩'], [/\bknown plaintext\b/gi, '已知明文'], [/\bcrib\b/gi, '猜测明文'],
  [/\bdash\b/gi, '短横线'], [/\bdigest\b/gi, '摘要'], [/\bdisable\b/gi, '禁用'],
  [/\bmatches\b/gi, '匹配'], [/\bbin\b/gi, '分箱'], [/\bempty\b/gi, '空'],
  [/\bwithin\b/gi, '以内'], [/\bdata\b/gi, '数据'], [/\bradius\b/gi, '半径'],
  [/\belliptic\b/gi, '椭圆'], [/\bemail\b/gi, '电子邮件'], [/\ballowed\b/gi, '允许'],
  [/\bchars?\b/gi, '字符'], [/\bspecial\b/gi, '特殊'], [/\bencoded\b/gi, '已编码'],
  [/\bencryption\b/gi, '加密'], [/\benumerate\b/gi, '枚举'], [/\bepoch\b/gi, '纪元'],
  [/\blanguage\b/gi, '语言'], [/\bextract(ions?)?\b/gi, '提取'], [/\bfilename\b/gi, '文件名'],
  [/\bfirst\b/gi, '首个'], [/\bletter\b/gi, '字母'], [/\bforce\b/gi, '强制'],
  [/\boptions?\b/gi, '选项'], [/\bglobal\b/gi, '全局'], [/\balign\b/gi, '对齐'],
  [/\bfrom\b/gi, '来自'], [/\bfailed\b/gi, '失败的'], [/\branges?\b/gi, '范围'],
  [/\bcompass directions?\b/gi, '罗盘方向'], [/\bfinal\b/gi, '最终'], [/\bnames?\b/gi, '名称'],
  [/\btokens?\b/gi, '令牌'], [/\barray\b/gi, '数组'], [/\bindent\b/gi, '缩进'],
  [/\binteger\b/gi, '整数'], [/\banswer\b/gi, '应答'], [/\bonly\b/gi, '仅'],
  [/\bmaster\b/gi, '主'], [/\bpanel\b/gi, '面板'], [/\bresize\b/gi, '调整大小'],
  [/\bafter\b/gi, '之后'], [/\bdecompression\b/gi, '解压'], [/\bschema\b/gi, '模式定义'],
  [/\blabel\b/gi, '标签'], [/\bpoint\b/gi, '点'], [/\bpack\b/gi, '打包'],
  [/\bby\b/gi, '按'], [/\bnegate\b/gi, '取反'], [/\bequals\b/gi, '等于'],
  [/\bcounter\b/gi, '计数器'], [/\bdiff\b/gi, '差异'], [/\bstyle\b/gi, '样式'],
  [/\bquality\b/gi, '质量'], [/\bper\b/gi, '每'], [/\brow\b/gi, '行'],
  [/\biteration(s)?\b/gi, '迭代次数'], [/\bfast\b/gi, '快速'], [/\bslow\b/gi, '慢速'],
  [/\bleft-most\b/gi, '最左侧'], [/\bleft-hand\b/gi, '左侧'], [/\bright-hand\b/gi, '右侧'],
  [/\bring setting\b/gi, '环位设置'], [/\bcontrol rotor\b/gi, '控制转子'],
  [/\bindex rotor\b/gi, '索引转子'], [/\bcipher rotor\b/gi, '密码转子'],
  [/\brotor(s)?\b/gi, '转子'], [/\breversed\b/gi, '反转'], [/\bstatic\b/gi, '静止'],
  [/\bmiddle\b/gi, '中间'], [/\binitialization\b/gi, '初始化'],
  [/\bhuman-readable part\b/gi, '人类可读部分'], [/\boperating system\b/gi, '操作系统'],
  [/\bnormal form\b/gi, '标准形式'], [/\bkeyboard emulation\b/gi, '键盘模拟'],
  [/\bwheel pattern\b/gi, '转轮模式'], [/\bprogram to run\b/gi, '要运行的程序'],
  [/\bhashing function\b/gi, '哈希函数'], [/\bencryption scheme\b/gi, '加密方案'],
  [/\bbuilt in\b/gi, '内置'], [/\bcarry through\b/gi, '原样传递'],
  [/\bnull preserving\b/gi, '保留空值'], [/\bcontext aware\b/gi, '感知上下文'],
  [/\bsyntax highlighting\b/gi, '语法高亮'], [/\binterface ID\b/gi, '接口 ID'],
  [/\bvalidation\b/gi, '验证'], [/\bcompatible\b/gi, '兼容'], [/\bcompatibility\b/gi, '兼容性'],
  [/\bautocrop\b/gi, '自动裁剪'], [/\btolerance\b/gi, '容差'], [/\bborder\b/gi, '边框'],
  [/\bbackground\b/gi, '背景'], [/\bopaque\b/gi, '不透明'], [/\baxis\b/gi, '坐标轴'],
  [/\bcapacity\b/gi, '容量'], [/\bcarriage returns?\b/gi, '回车符'], [/\bform feeds?\b/gi, '换页符'],
  [/\bfull stops?\b/gi, '句号'], [/\bsegment\b/gi, '段'], [/\bdeletion\b/gi, '删除'],
  [/\binsertion\b/gi, '插入'], [/\bsubstitution\b/gi, '替换'], [/\bcost\b/gi, '成本'],
  [/\bdraw\b/gi, '绘制'], [/\bedges?\b/gi, '边缘'], [/\bhexagons?\b/gi, '六边形'],
  [/\bboundaries\b/gi, '边界'], [/\bcurve\b/gi, '曲线'], [/\bescape\b/gi, '转义'],
  [/\brestore\b/gi, '恢复'], [/\bdots?\b/gi, '点'], [/\bquotes?\b/gi, '引号'],
  [/\blevels?\b/gi, '级别'], [/\bextensive\b/gi, '扩展'], [/\bfont\b/gi, '字体'],
  [/\bface\b/gi, '字形'], [/\bgranularity\b/gi, '粒度'], [/\binterval\b/gi, '间隔'],
  [/\binvert\b/gi, '反转'], [/\bcondition\b/gi, '条件'], [/\bquality\b/gi, '质量'],
  [/\bkeyword\b/gi, '关键词'], [/\bpenalty\b/gi, '惩罚'], [/\blimitation\b/gi, '限制'],
  [/\blocation\b/gi, '位置'], [/\bmargin\b/gi, '边距'], [/\bmodules?\b/gi, '模块'],
  [/\bfactor\b/gi, '因子'], [/\bnamespace\b/gi, '命名空间'], [/\bframes?\b/gi, '帧'],
  [/\bparallelism\b/gi, '并行度'], [/\bparallelization\b/gi, '并行化'], [/\bpixel(s)?\b/gi, '像素'],
  [/\bplugboard\b/gi, '插头板'], [/\bpolynomial\b/gi, '多项式'], [/\bquery\b/gi, '查询'],
  [/\bradix\b/gi, '基数'], [/\brange\b/gi, '范围'], [/\breflectors?\b/gi, '反射器'],
  [/\bresolver\b/gi, '解析器'], [/\brules?\b/gi, '规则'], [/\bscope\b/gi, '作用域'],
  [/\bsemicolons?\b/gi, '分号'], [/\bbraces?\b/gi, '花括号'], [/\bsequential\b/gi, '顺序'],
  [/\bbonus\b/gi, '加成'], [/\bspaces?\b/gi, '空格'], [/\bstandard\b/gi, '标准'],
  [/\bstrikethrough\b/gi, '删除线'], [/\bsubnet\b/gi, '子网'], [/\bsymmetric\b/gi, '对称'],
  [/\btemplate\b/gi, '模板'], [/\bdefinition\b/gi, '定义'], [/\btime\b/gi, '时间'],
  [/\boperation\b/gi, '操作'], [/\btranslation\b/gi, '转换'], [/\bunderline\b/gi, '下划线'],
  [/\bunderscore\b/gi, '下划线'], [/\bunits?\b/gi, '单位'], [/\bverify\b/gi, '验证'],
  [/\bresult\b/gi, '结果'], [/\bvideo\b/gi, '视频'], [/\bvisualisation\b/gi, '可视化'],
  [/\bwitness\b/gi, '见证'], [/\bzoom\b/gi, '缩放'], [/\blugs?\b/gi, '凸轮'],
  [/\bapplications?\b/gi, '应用'], [/\barchives?\b/gi, '归档'], [/\bdocuments?\b/gi, '文档'],
  [/\bformat(s)?\b/gi, '格式'], [/\bregexes\b/gi, '正则表达式'],
  [/\bconvert\b/gi, '转换'], [/\bsigned\b/gi, '有符号'], [/\bdisplay\b/gi, '显示'],
  [/\btotal\b/gi, '总计'], [/\bdrop\b/gi, '丢弃'], [/\bevery\b/gi, '每'],
  [/\bfast\b/gi, '快速'], [/\bslow\b/gi, '慢速'], [/\bstep\b/gi, '步进'],
  [/\baddition\b/gi, '加法'], [/\bconditional\b/gi, '条件'], [/\bmain\b/gi, '主'],
  [/\bmiscellaneous\b/gi, '其他'], [/\bmodel\b/gi, '型号'], [/\bpacked\b/gi, '已打包'],
  [/\braw\b/gi, '原始'], [/\binfo\b/gi, '信息'], [/\bprocess\b/gi, '处理'],
  [/\balpha\b/gi, '透明度'], [/\bastral\b/gi, '辅助平面'], [/\bsupport\b/gi, '支持'],
  [/\bkey pair\b/gi, '密钥对'], [/\bprivate key\b/gi, '私钥'], [/\bpublic key\b/gi, '公钥'],
  [/\bemail addresses?\b/gi, '电子邮件地址'], [/\bIP addresses?\b/gi, 'IP 地址'],
  [/\bMAC addresses?\b/gi, 'MAC 地址'], [/\bfile paths?\b/gi, '文件路径'],
  [/\bdata units?\b/gi, '数据单位'], [/\bline numbers?\b/gi, '行号'],
  [/\bpassphrase\b/gi, '口令'], [/\bcertificate(s)?\b/gi, '证书'],
  [/\bbrightness\b/gi, '亮度'], [/\bcontrast\b/gi, '对比度'],
  [/\bsaturation\b/gi, '饱和度'], [/\blightness\b/gi, '明度'],
  [/\barea\b/gi, '面积'], [/\bdistance\b/gi, '距离'], [/\bmass\b/gi, '质量'],
  [/\bspeed\b/gi, '速度'], [/\bdate(s)?\b/gi, '日期'], [/\bdomain(s)?\b/gi, '域名'],
  [/\bchecksum(s)?\b/gi, '校验和'], [/\bsignature\b/gi, '签名'],
  [/\bcharacters?\b/gi, '字符'], [/\bstring(s)?\b/gi, '字符串'],
  [/\baudio\b/gi, '音频'], [/\bmetadata\b/gi, '元数据'],
  [/\bname\b/gi, '名称'], [/\btimestamp\b/gi, '时间戳'],
  [/\bpalette\b/gi, '调色板'], [/\btags?\b/gi, '标签'],
  [/\bsequence\b/gi, '序列'],
  [/\binput\b/gi, '输入'], [/\boutput\b/gi, '输出'],
  [/\bformat\b/gi, '格式'], [/\btype\b/gi, '类型'], [/\bmode\b/gi, '模式'],
  [/\bdelimiter(s)?\b/gi, '分隔符'], [/\blength\b/gi, '长度'], [/\bsize\b/gi, '大小'],
  [/\bkey\b/gi, '密钥'], [/\bpassword\b/gi, '密码'], [/\bprivate\b/gi, '私有'],
  [/\bpublic\b/gi, '公开'], [/\bencoding\b/gi, '编码'], [/\bdecode\b/gi, '解码'],
  [/\bencode\b/gi, '编码'], [/\bhash(es)?\b/gi, '哈希'], [/\bcipher\b/gi, '密码'],
  [/\bimage(s)?\b/gi, '图像'], [/\bfile(s)?\b/gi, '文件'], [/\bline(s)?\b/gi, '行'],
  [/\bcharacter(s)?\b/gi, '字符'], [/\bbyte(s)?\b/gi, '字节'], [/\bword(s)?\b/gi, '单词'],
  [/\bnumber(s)?\b/gi, '数字'], [/\bcolour(s)?\b/gi, '颜色'], [/\bcolor(s)?\b/gi, '颜色'],
  [/\bwidth\b/gi, '宽度'], [/\bheight\b/gi, '高度'], [/\bposition\b/gi, '位置'],
  [/\bstarting\b/gi, '起始'], [/\bstart\b/gi, '开始'], [/\bend\b/gi, '结束'],
  [/\binclude\b/gi, '包含'], [/\bignore\b/gi, '忽略'], [/\bremove\b/gi, '移除'],
  [/\bshow\b/gi, '显示'], [/\buse\b/gi, '使用'], [/\ball\b/gi, '全部'],
  [/\bcase\b/gi, '大小写'], [/\buppercase\b/gi, '大写'], [/\blowercase\b/gi, '小写'],
  [/\boptional\b/gi, '可选'], [/\bseparator\b/gi, '分隔符'], [/\boffset\b/gi, '偏移量'],
  [/\bvalue(s)?\b/gi, '值'], [/\bcount\b/gi, '数量'], [/\bamount\b/gi, '数量'],
  [/\balgorithm\b/gi, '算法'], [/\bmethod\b/gi, '方法'], [/\boption\b/gi, '选项'],
  [/\bmatch(ing)?\b/gi, '匹配'], [/\bregex\b/gi, '正则'], [/\bheader(s)?\b/gi, '头部'],
  [/\bmetadata\b/gi, '元数据'], [/\bvalid\b/gi, '有效'], [/\berror(s)?\b/gi, '错误'],
  [/\bnetwork\b/gi, '网络'], [/\baddress(es)?\b/gi, '地址'], [/\btimezone\b/gi, '时区'],
  [/\bhorizontal\b/gi, '水平'], [/\bvertical\b/gi, '垂直'], [/\bmaximum\b/gi, '最大'],
  [/\bminimum\b/gi, '最小'], [/\bmax\b/gi, '最大'], [/\bmin\b/gi, '最小'],
];

export function localizeCyberChefCategory(name: string, language?: string): string {
  return cyberChefLanguage(language) === 'zh' ? (ZH_CATEGORIES[name] ?? name) : name;
}

function replaceKnownText(text: string): string {
  const exact = ZH_TERMS[text];
  if (exact) return exact;

  let translated = text;
  for (const [pattern, target] of WORD_TERMS) translated = translated.replace(pattern, target);
  // English source uses spaces as word separators. Remove those that become
  // redundant between two translated Chinese fragments while retaining the
  // useful boundary around names such as "RSA 密钥".
  return translated
    .replace(/([\u3400-\u9fff])\s+([\u3400-\u9fff])/g, '$1$2')
    .replace(/([\u3400-\u9fff])\s+([\u3400-\u9fff])/g, '$1$2')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

export function localizeCyberChefOperation(name: string, language?: string): string {
  if (cyberChefLanguage(language) !== 'zh') return name;
  if (ZH_EXACT[name]) return ZH_EXACT[name];

  if (name.startsWith('From ')) return `从 ${replaceKnownText(name.slice(5))} 解码`;
  if (name.startsWith('To ')) return `编码为 ${replaceKnownText(name.slice(3))}`;

  for (const [prefix, translation] of OP_PREFIXES) {
    if (name.startsWith(prefix)) {
      const rest = replaceKnownText(name.slice(prefix.length));
      return `${translation}${/^[\x00-\x7f]/.test(rest) ? ' ' : ''}${rest}`;
    }
  }
  for (const [suffix, translation] of OP_SUFFIXES) {
    if (name.endsWith(suffix)) {
      return `${replaceKnownText(name.slice(0, -suffix.length))}${translation}`
        .replace(/([\u3400-\u9fff])\s+([\u3400-\u9fff])/g, '$1$2');
    }
  }
  return replaceKnownText(name);
}

export function localizeCyberChefIngredient(text: string, language?: string): string {
  return cyberChefLanguage(language) === 'zh' ? replaceKnownText(text) : text;
}
