import { memo, useState } from 'react';
import { useTranslation } from 'react-i18next';
// @ts-expect-error -- vendored json-to-go has no type declarations
import { jsonToGo } from '../lib/json-to-go.js';
import CopyButton from '../components/CopyButton';
import GlassInput from '../components/GlassInput';
import ToolLayout from '../components/ToolLayout';

const initial = '{\n  "name": "toolbox",\n  "stars": 1024,\n  "tags": ["misc", "web"],\n  "author": { "name": "local", "since": 2024 }\n}';

const JsonToGoTool = memo(function JsonToGoTool() {
  const { t } = useTranslation();
  const [json, setJson] = useState(initial);
  const [typeName, setTypeName] = useState('AutoGenerated');

  let output = '';
  let error = '';
  try {
    const result = jsonToGo(json, typeName || 'AutoGenerated') as { go: string; error?: string };
    if (result.error) error = result.error;
    else output = result.go;
  } catch {
    error = t('tools.json-to-go.error');
  }

  return (
    <ToolLayout id="json-to-go" color="#4ade80">
      <div className="flex flex-col gap-4">
        <label className="text-sm text-[var(--color-text-muted)]">
          {t('tools.json-to-go.typeName')}
          <GlassInput aria-label={t('tools.json-to-go.typeName')} value={typeName} onChange={(e) => setTypeName(e.target.value)} className="mt-1 sm:max-w-xs" />
        </label>
        <div className="grid gap-5 lg:grid-cols-2">
          <div>
            <h2 className="mb-2 font-semibold">JSON</h2>
            <GlassInput multiline aria-label="JSON" rows={16} className={`font-mono ${error ? 'border-red-400/60' : ''}`} value={json} onChange={(e) => setJson(e.target.value)} placeholder='{ "key": "value" }' />
          </div>
          <div>
            <div className="mb-2 flex items-center justify-between">
              <h2 className="font-semibold">Go</h2>
              <CopyButton value={output} />
            </div>
            <GlassInput multiline readOnly aria-label="Go" rows={16} className="font-mono" value={error ? '' : output} onChange={() => {}} />
            {error && <p className="mt-2 text-sm text-red-500 dark:text-red-300">{error}</p>}
          </div>
        </div>
      </div>
    </ToolLayout>
  );
});

export default JsonToGoTool;
